version: '3.3'

networks:
  containerNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.50.60.0/29
#Jenkins service
services:
  jenkins:
      restart: always
      container_name: jenkins_service
      build:
          context: ./jenkins_service/
          dockerfile: Dockerfile
      ports:
          - "8080:8080"
          - "50000:50000"
          - "8070:22"
      volumes:
        - ./jenkins_service/jenkins_config:/root/.jenkins
      networks:
        containerNetwork:
          ipv4_address: 10.50.60.2
      privileged: true