global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-target-1:9090']
  - job_name: 'data_collector_metrics'
    scrape_interval: 5s
    static_configs: 
      - targets: ['10.10.10.19:8080','10.10.10.19:9100']
        labels:
          machine_name: data_collector
  - job_name: 'traefik_metrics'
    scrape_interval: 5s
    static_configs: 
      - targets: ['10.10.10.3:8090','10.10.10.3:9100']
        labels:
          machine_name: traefik