server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://10.50.60.5:3100/loki/api/v1/push

#Syslog
scrape_configs:
  - job_name: local
    static_configs:
    - targets:
        - localhosts
      labels:
        job: syslog
        __path__: /logs/*log